logging:
  level: INFO
  loggers:
    com.thrive: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080

shards:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: admin
      password:
      url: jdbc:mariadb://ec2-user-database-1..us-east-1.rds.amazonaws.com:3306/user_service_shard_1?createDatabaseIfNotExist=true
      minSize: 2
      maxSize : 2
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
    - driverClass: org.mariadb.jdbc.Driver
      user: admin
      password:
      url: jdbc:mariadb://ec2-user-database-1..us-east-1.rds.amazonaws.com:3306/user_service_shard_2?createDatabaseIfNotExist=true
      minSize: 2
      maxSize: 2
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect

caches:
  mapConfig:
    USER:
      ttl : 100
      ttlType : SECONDS

redis:
  singleServerConfig:
    idleConnectionTimeout: 10000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    password: null
    subscriptionsPerConnection: 5
    clientName: null
    address: "redis://127.0.0.1:6379"
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 2
    connectionPoolSize: 2
    database: 0
    dnsMonitoringInterval: 5000